### ISSUE TITLE
[Core] Get rid of auto value class and replace with kotlin

### ISSUE THREAD

**Issue by noorejannat** [amardeshbd/android-daily-headlines#187]
AutoValue is no longer required as kotlin data class does the job.
As part of task, should introduce kotlin to tablet module [OPTIONAL, or leave it for historical purpose].

**Comment by amardeshbd** [comment]
This may be duplicate of #195

**Comment by amardeshbd** [comment]
Fixed in https://github.com/amardeshbd/android-daily-headlines/issues/195
